// ─── The generated command index ──────────────────────────────────────────────
//
// ⚠️ `command-index.json` is GENERATED by `scripts/sync-command-index.mjs` from
// the CLI binary's own clap tree. Do not edit it, and do not add a list of
// commands here.
//
// This is what `EVNX_COMMANDS` tried to be. That constant was hand-written and
// omitted `spec` entirely — the same shape of error has happened five times in
// this project, and every one was found by a hand sweep, which does not repeat.

import data from "./command-index.json";

export interface IndexedSubcommand {
  /** `vault share` — the full invocation, without `evnx`. */
  path: string;
  about: string | null;
}

export interface IndexedCommand {
  name: string;
  about: string | null;
  aliases: string[];
  /**
   * Author-form path (`/guides/commands/scan`), which `DOCS_MODE` rewrites at
   * render time. ⚠️ Never the rendered `/cli/…` form — writing that produces
   * links dead on the live site.
   *
   * `null` when the command has no guide yet, which is a legitimate state: a
   * command may ship before its guide.
   */
  guide: string | null;
  /** The guide exists but is unlisted. Still reachable, still worth linking. */
  guide_draft: boolean;
  subcommands: IndexedSubcommand[];
}

export interface CommandIndex {
  schema: number;
  evnx_version: string;
  features: string[];
  commands: IndexedCommand[];
  /** Commands with no guide. ⚠️ Baked in, so a new gap shows in the diff. */
  undocumented: string[];
  /** Guides documenting a command that no longer exists. Should be empty. */
  orphan_guides: string[];
}

export const COMMAND_INDEX = data as CommandIndex;

/** The CLI version this index describes. Shown, because it will go stale. */
export const INDEXED_EVNX_VERSION = COMMAND_INDEX.evnx_version;

/** Every command and subcommand, counted the way a reader would count them. */
export function commandCount(): number {
  return COMMAND_INDEX.commands.reduce((n, c) => n + 1 + c.subcommands.length, 0);
}
